name: resnet
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  # - cudatoolkit=11.3
  - pytorch
  - torchvision
  - numpy
  - pip:
      - pytorch-lightning
      - transformers
      - matplotlib